apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threatrecall-data
  labels:
    app: threatrecall-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
