apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: threatrecall-production

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: threatrecall-api
    count: 3

patches:
  - target:
      kind: Ingress
      name: threatrecall-api
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: api.threatrecall.local
  - target:
      kind: Deployment
      name: threatrecall-api
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 2000m
  - target:
      kind: PersistentVolumeClaim
      name: threatrecall-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 100Gi
