apiVersion: velero.io/v1
kind: Restore
metadata:
  name: threatrecall-restore
  namespace: velero
spec:
  backupName: threatrecall-daily-20240406020000
  includedNamespaces:
    - threatrecall-production
  labelSelector:
    matchLabels:
      app: threatrecall-api
  restorePVs: true
