apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: threatrecall-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: threatrecall-api
    count: 1

patches:
  - target:
      kind: Ingress
      name: threatrecall-api
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: api-staging.threatrecall.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api-staging.threatrecall.local
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-threatrecall-api-tls
  - target:
      kind: PersistentVolumeClaim
      name: threatrecall-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
